version: "3.5"
services:
#  server:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db1
#      - db2
#      - db3
  db1:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ddbs
      MYSQL_ROOT_PASSWORD: zyven
    ports:
      - "4000:3306"
  db2:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ddbs
      MYSQL_ROOT_PASSWORD: zyven
    ports:
      - "4001:3306"
  db3:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ddbs
      MYSQL_ROOT_PASSWORD: zyven
    ports:
      - "4002:3306"
  ddbs:
    image: redis:latest
    ports:
      - "6379:6379"